appveen/ds-ui-author

src/app/home/control-panel/user/user-grid-action.component.ts, src/app/home/control-panel/user/user-to-group-modal/user-to-group-modal.component.ts, src/app/home/control-panel/user/user.component.html, src/app/home/control-panel/user/user.component.ts, src/app/home/local-bot/local-bot-cell-renderer/local-bot-cell-renderer.component.html, src/app/home/local-bot/local-bot.component.html, src/app/home/local-bot/local-bot.component.ts, src/app/home/local-bot/local-bot.module.ts, src/app/home/local-bot/manage-bot-group/manage-bot-group.component.ts, src/app/home/local-bot/manage-bot-key/manage-bot-key.component.html, src/app/home/local-bot/manage-bot-key/manage-bot-key.component.ts, src/app/home/local-bot/manage-bot-property/manage-bot-property.component.ts, src/app/utils/ag-grid-actions-renderer/ag-grid-actions-renderer.component.html, src/app/utils/ag-grid-actions-renderer/ag-grid-actions-renderer.component.scss, src/app/utils/ag-grid-actions-renderer/ag-grid-actions-renderer.module.ts, src/app/utils/delete-modal/delete-modal.component.html, src/app/utils/delete-modal/delete-modal.component.scss, src/app/utils/delete-modal/delete-modal.component.ts
Took care of the ag-grid warnings and added alerts to bot actions
=> Fixes after reviews -4

src/app/home/faas/faas-listing/faas-listing.component.ts
=> Possible fix for DEF2156

src/app/home/faas/faas-listing/faas-listing.component.html, src/app/home/faas/faas-listing/faas-listing.component.scss
=> DEF2341 is fixed

src/app/home/app-manage/app-manage.component.scss, src/app/home/global-schemas/global-schemas.component.scss, src/app/utils/app-center-preview/app-center-preview.component.scss
=> DEF1499 is fixed

src/app/home/b2b-flows/b2b-flows.component.html, src/app/home/b2b-flows/b2b-flows.component.scss, src/app/home/faas/faas-listing/faas-listing.component.scss
=> Def2364 is fixed

src/app/utils/structure-field-properties/text-property/text-property.component.html
=> DEF1005 is fixed

src/app/apps/apps.component.html, src/app/apps/apps.component.scss, src/app/home/connectors-manage/connectors-manage.component.html, src/app/home/connectors/connectors.component.html
=> side-panel fix

src/app/home/service-manager/service-manager.component.ts
=> DEF2370 is fixed

src/app/home/b2b-flows-manage/b2b-flows-manage.component.scss
=> DEF2408 is fixed

src/app/apps/apps.component.ts, src/app/home/connectors-manage/connectors-manage.component.ts, src/app/home/service-manager/service-manager.component.ts, src/app/utils/services/common.service.ts
=> DEF2410 is fixed

src/app/home/b2b-flows-manage/flow-node/flow-node.component.html, src/app/home/b2b-flows-manage/flow-node/flow-node.component.ts
=> DEF2351 is fixed

src/app/home/local-bot/local-bot.component.ts
=> DEF2418 is fixed

src/app/home/service-manager/service-manager.component.html
=> DEF2061 is fixed

src/app/admin/app-list/app-list.component.html, src/app/admin/app-list/app-list.component.ts
=> DEF2428 is fixed

src/app/utils/structure-field/structure-field.component.ts
=> DEF1483 is fixed

src/app/home/connectors-manage/connectors-manage.component.html, src/app/home/connectors/connectors.component.html, src/app/home/connectors/connectors.component.scss, src/app/home/data-format-listing/data-format-listing.component.html, src/app/home/data-format-listing/data-format-listing.component.scss, src/app/home/library/library.component.html, src/app/home/library/library.component.scss
=> DEF2431 & DEF2432 is fixed

src/app/home/schema-utils/wizards/step-fields/step-fields.component.ts, src/app/utils/structure-field-properties/relation-property/relation-property.component.ts
=> DEF2437 is fixed

src/app/home/schema-utils/state-model/state-model.component.html, src/app/home/schema-utils/state-model/state-model.component.ts
=> STORY1115 changes

src/app/utils/structure-field-properties/relation-property/relation-property.component.ts
=> DEF1610 is fixed

package.json
=> Updating package

src/app/home/schema-utils/manage-permissions/manage-permissions.component.html
=> DEF2455 is fixed

src/app/home/profile/profile.component.ts, src/app/utils/change-password/change-password.component.ts
=> DEF2456 is fixed

src/app/home/schema-utils/state-model/state-model.component.html
=> DEF2463 is fixed

src/app/home/b2b-flows-manage/flow-node/flow-node.component.ts, src/app/home/b2b-flows-manage/node-properties/node-properties.component.html, src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts
=> Defect DEF2468 fixed

src/app/home/b2b-flows/b2b-flows.component.html
=> Defect DEF2477 fixed

src/app/home/b2b-flows/b2b-flows.component.html
=> Removing redundant code

src/app/home/b2b-flows/b2b-flows.component.html, src/app/home/b2b-flows/b2b-flows.component.ts
=> Defect DEF2489 fixed

src/app/utils/field-type/field-type-selector/field-type-selector.component.html, src/app/utils/field-type/field-type-selector/field-type-selector.component.scss, src/app/utils/field-type/field-type-selector/field-type-selector.component.ts
=> Defect DEF2496 fixed

src/app/home/b2b-flows/b2b-flows.component.html, src/app/home/b2b-flows/b2b-flows.component.scss
=> Defect DEF2499 fixed

src/app/home/b2b-flows/b2b-flows.component.ts
=> DEF2503 is fixed.

src/app/home/b2b-flows-manage/node-properties/node-data-selector/node-data-selector.component.ts
=> Defect DEF2511 fixed

src/app/home/api-keys/api-keys-manage/list-flow/list-flow.component.ts, src/app/home/api-keys/api-keys-manage/list-function/list-function.component.ts
=> API Keys changes for flow and function

src/app/home/b2b-flows-manage/b2b-flows-manage.component.html, src/app/home/b2b-flows-manage/b2b-flows-manage.component.ts, src/app/home/b2b-flows-manage/node-properties/input-data-selector/input-data-selector.component.html, src/app/home/b2b-flows/b2b-flows.component.ts, src/app/home/schema-utils/state-model/state-model.component.html
=> DEF2423, DEF2513, DEF2512 and DS-9 is fixed

src/app/home/api-keys/api-keys-manage/list-flow/list-flow.component.ts, src/app/home/api-keys/api-keys-manage/list-function/list-function.component.ts
=> Undo entity and id change

src/app/apps/apps.component.html
=> Side nav Flows permission on author

src/app/home/b2b-flows/b2b-flows.component.html, src/app/home/b2b-flows/b2b-flows.component.ts
=> DEF2488 is fixed

src/app/home/agents/agent-view/agent-logs/agent-logs.component.html, src/app/home/agents/agent-view/agent-logs/agent-logs.component.scss, src/app/home/agents/agent-view/agent-logs/agent-logs.component.ts, src/app/home/agents/agent-view/agent-view.component.html, src/app/home/agents/agents.component.html, src/app/home/agents/agents.component.ts
=> DS-312 is fixed

src/app/home/control-panel/user-group/user-group-manage/user-group-appcenter/user-group-appcenter-flows/user-group-appcenter-flows.component.ts
=> DS-309 fix

src/app/home/agents/agent-view/agent-logs/agent-logs.component.html, src/app/home/agents/agent-view/agent-logs/agent-logs.component.scss, src/app/home/agents/agent-view/agent-view.component.ts
=> DS-332 is fixed

src/app/home/b2b-flows-manage/b2b-flows-manage.component.ts, src/app/home/b2b-flows/b2b-flows.component.ts, src/app/utils/services/app.service.ts
=> DS-328 is fixed

src/app/home/agents/agents.component.html, src/app/home/agents/agents.component.ts
=> DS-314 fix

src/app/home/agents/agent-view/agent-view.component.html, src/app/home/agents/agents.component.html, src/app/home/agents/agents.component.ts
=> DS-337 is fixed

src/app/home/agents/agents.component.ts, src/app/home/b2b-flows/b2b-flows.component.html, src/app/home/b2b-flows/b2b-flows.component.ts
=>   DS-336 and DS-335 is fixed

src/app/home/agents/agent-view/agent-logs/agent-logs.component.ts, src/app/home/agents/agents.component.html, src/app/home/agents/agents.component.ts, src/app/home/b2b-flows/b2b-flows.component.html, src/app/home/b2b-flows/b2b-flows.component.ts, src/app/login/login.component.html
=> DS-339, DS-341, DS-343 and DS-345 is fixed

src/app/home/b2b-flows/b2b-flows.component.html, src/app/home/b2b-flows/b2b-flows.component.ts
=> DS-346 is fixed.

src/app/home/b2b-flows/b2b-flows.component.ts
=> DS-347 is fixed

src/app/home/b2b-flows/b2b-flows.component.html, src/app/home/b2b-flows/b2b-flows.component.ts
=> DS-353 is fixed.

src/app/home/agents/agent-view/agent-sessions/agent-sessions.component.html, src/app/home/agents/agent-view/agent-view.component.html, src/app/home/agents/agent-view/agent-view.component.ts, src/app/home/agents/agents.component.html, src/app/home/agents/agents.component.ts
=> DS-318, DS-317, DS-319 and DS-339 is fixed

src/app/home/agents/agent-view/agent-sessions/agent-sessions.component.ts
=> DS-319 is fixed

src/app/home/agents/agents.component.html, src/app/home/data-format-listing/data-format-listing.component.html
=> DS-352 is fixed.

src/app/home/agents/agent-view/agent-logs/agent-logs.component.html, src/app/home/agents/agents.component.scss, src/app/home/data-format-listing/data-format-listing.component.html, src/app/home/data-format-listing/data-format-listing.component.ts
=> DS-351 is fixed

src/app/home/control-panel/user-group/user-group-manage/user-group-appcenter/user-group-appcenter-flows/user-group-appcenter-flows.component.ts
=> DS-349 is fixed.

src/app/home/b2b-flows-manage/b2b-flows-manage.component.ts
=> Defect DS-340 fixed

src/app/home/b2b-flows-manage/b2b-flow.service.ts, src/app/home/b2b-flows-manage/node-properties/input-data-selector/input-data-selector.component.html, src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts, src/app/home/b2b-flows-manage/path-properties/path-condition-creator/path-condition-creator.component.ts, src/app/home/b2b-flows-manage/path-properties/path-properties.component.html, src/app/utils/payload-creator/payload-array/payload-array.component.html, src/app/utils/payload-creator/payload-array/payload-array.component.ts, src/app/utils/payload-creator/payload-creator.component.html, src/app/utils/payload-creator/payload-creator.component.ts, src/app/utils/payload-creator/payload-field/payload-field.component.html, src/app/utils/payload-creator/payload-field/payload-field.component.ts, src/app/utils/payload-creator/payload-object/payload-object.component.html, src/app/utils/payload-creator/payload-object/payload-object.component.ts
@jugnu-appveen - this can be merged after today's call as well.
=> Previous node in path and payload

src/app/home/b2b-flows-manage/b2b-flow.service.ts
@jugnu-appveen - added the body and response body
=> Adding body and response body

src/app/home/agents/agents.component.html, src/app/home/agents/agents.component.ts, src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.scss
=> DS-371 is fixed

src/app/home/control-panel/user/user.component.html
=> DS-363 is fixed

src/app/home/b2b-flows-manage/node-properties/add-headers/add-headers.component.html, src/app/home/b2b-flows-manage/node-properties/add-headers/add-headers.component.ts, src/app/home/b2b-flows-manage/node-properties/node-properties.component.html, src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts, src/app/utils/styled-text/styled-text.component.html, src/app/utils/styled-text/styled-text.component.scss, src/app/utils/styled-text/styled-text.component.ts
=> Adding autocomplete on headers and url

src/app/home/control-panel/user-group/user-group-manage/user-group-appcenter/user-group-appcenter-services/user-group-appcenter-services.component.html, src/app/home/control-panel/user-group/user-group-manage/user-group-appcenter/user-group-appcenter-services/user-group-appcenter-services.component.scss, src/app/home/control-panel/user-group/user-group-manage/user-group-appcenter/user-group-appcenter-services/user-group-appcenter-services.component.ts, src/app/home/control-panel/user-group/user-group-manage/user-group-appcenter/user-group-appcenter.component.html, src/app/home/control-panel/user-group/user-group-manage/user-group-appcenter/user-group-appcenter.component.ts, src/app/home/control-panel/user-group/user-group-manage/user-group-manage.component.html
=> DS-181 is fixed

src/app/home/b2b-flows-manage/node-properties/input-data-selector/input-data-selector.component.html
=> DS-384 is fixed

src/app/home/control-panel/user-group/user-group.component.ts
=> DS-382 is fixed.

src/app/utils/search-box/search-box.component.ts
=> DS-381 is fixed.

src/app/home/schema-utils/wizards/step-actions/step-actions.component.html
=> DS-389 is fixed.

src/app/admin/admin.component.ts, src/app/apps/apps.component.ts, src/app/home/b2b-flows-manage/b2b-flows-manage.component.ts, src/app/home/b2b-flows/b2b-flows.component.ts, src/app/home/control-panel/user/bulk-import/bulk-import.component.ts, src/app/home/faas/faas-listing/faas-listing.component.ts, src/app/home/home/home.component.ts, src/app/home/schema-builder/schema-builder.component.ts, src/app/home/service-manager/service-manager.component.ts, src/app/utils/services/common.service.old.ts, src/app/utils/services/common.service.ts
=> Long Polling

src/app/utils/data-structure-selector/data-format-selector/data-format-selector.component.ts
=> DS-391 is fixed

src/app/app.module.ts, src/app/home/b2b-flows-manage/b2b-flows-manage.module.ts, src/app/home/b2b-flows-manage/node-properties/node-properties.component.html, src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts, src/app/utils/autocomplete-on-edit/autocomplete-on-edit.component.html, src/app/utils/autocomplete-on-edit/autocomplete-on-edit.component.scss, src/app/utils/autocomplete-on-edit/autocomplete-on-edit.component.spec.ts, src/app/utils/autocomplete-on-edit/autocomplete-on-edit.component.ts, src/app/utils/autocomplete-on-edit/autocomplete-on-edit.module.ts, src/app/utils/pipes/filter-app.module.ts
@jugnu-appveen - created a component that can be used which consists of autocomplete as well as edit option with save and cancel. Replaced the url field on the invoke api node.
=> Autocomplete component with on edit

src/app/home/service-manager/service-manager.component.ts, src/app/utils/services/common.service.ts
=> fixed wrong toastr shown on starting DS

src/app/home/data-format-listing/data-format-listing.component.ts, src/app/home/data-format-manage/data-format-manage.component.ts
=> DS-394 is fixed

src/app/utils/editor/editor.directive.ts, src/app/utils/styled-text/styled-text.component.ts
=> Defect DS-387 fixed

src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.html, src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.ts, src/app/home/b2b-flows-manage/node-properties/node-properties.component.html, src/app/utils/styled-text/styled-text.component.html
=> DS-398 is fixed

src/app/utils/styled-text/styled-text.component.scss, src/app/utils/styled-text/styled-text.component.ts
=> DS-402 is fixed

src/app/home/b2b-flows/b2b-flows.component.ts
=> Defect DS-386 fixed

src/app/home/faas/faas-listing/faas-listing.component.html, src/app/home/faas/faas-listing/faas-listing.component.ts, src/app/home/faas/faas-manage/faas-manage.component.ts, src/app/utils/services/app.service.ts
=> DS-403 is fixed

src/app/home/b2b-flows-manage/node-properties/node-mapping/formula-editor/formula-editor.component.html
=> Taking care of delete on styled component

src/app/home/faas/faas-listing/faas-listing.component.ts
=> DS-405 is fixed

src/app/home/b2b-flows-manage/node-properties/node-properties.component.html, src/app/home/b2b-flows-manage/node-properties/node-properties.component.scss, src/app/home/faas/faas-listing/faas-listing.component.ts
=> DS-396 is fixed

src/app/home/b2b-flows/b2b-flows.component.ts
=> DS-404 is fixed

src/app/home/b2b-flows-manage/b2b-flows-manage.component.html, src/app/home/b2b-flows-manage/b2b-flows-manage.component.scss, src/app/home/b2b-flows-manage/b2b-flows-manage.component.ts, src/app/home/b2b-flows-manage/flow-node/flow-node.component.html, src/app/home/b2b-flows-manage/flow-node/flow-node.component.scss, src/app/home/b2b-flows-manage/flow-node/flow-node.component.ts, src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.html, src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.scss, src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.ts
=> Defect fix

src/app/home/data-format-listing/data-format-listing.component.ts
=> Defect DS-408 fixed

src/app/home/data-format-manage/data-format-manage.component.html, src/app/home/data-format-manage/data-format-manage.component.ts, src/app/utils/basic-info/basic-info.component.ts
=> DS-412 - validate text pattern while editing the data format name

src/app/home/b2b-flows-manage/node-properties/node-mapping/target-fields/target-fields.component.scss, src/app/home/b2b-flows-manage/node-properties/node-properties.component.html, src/app/home/b2b-flows-manage/node-properties/node-properties.component.scss, src/app/utils/field-type/field-type.component.html
=> Mapping screen minor changes

src/app/home/schema-builder/schema-builder.component.ts, src/app/home/schema-utils/configuration/data-settings/data-settings.component.html, src/app/home/schema-utils/configuration/data-settings/data-settings.component.ts
=> Simple date author changes

src/app/home/b2b-flows-manage/node-properties/connector-properties/mongodb-connector/mongodb-connector.component.html, src/app/home/b2b-flows-manage/node-properties/connector-properties/mongodb-connector/mongodb-connector.component.ts, src/app/home/b2b-flows-manage/node-properties/input-data-selector/input-data-selector.component.html, src/app/utils/change-on-edit/change-on-edit.component.html, src/app/utils/change-on-edit/change-on-edit.component.scss, src/app/utils/data-structure-selector/data-structure-selector.component.html
=> Mongo query field added

src/app/home/control-panel/user-group/user-group-manage/user-group-appcenter/user-group-appcenter-flows/user-group-appcenter-flows.component.ts
=> Wrong filter issue fix

src/app/home/b2b-flows-manage/flow-node/flow-node.component.html, src/app/home/b2b-flows-manage/flow-node/flow-node.component.ts
@jugnu-appveen - the big chunk of code removed is part of keeping the components for process flow and data pipes separate.
=> Defect DS-411 fixed

src/app/home/b2b-flows/b2b-flows.component.ts
=> Defect DS-499 fixed

src/app/home/data-format-listing/data-format-listing.component.ts
=> Defect DS-521 fixed

src/app/admin/user-list/user-list.component.ts, src/app/utils/services/common.service.ts
=> Defect DS-548 fixed

src/app/home/b2b-flows-manage/node-properties/converter-properties/converter-properties.component.html, src/app/home/b2b-flows-manage/node-properties/node-mapping/mapping.service.ts, src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.ts
@jugnu-appveen - added a few null checks and a condition to take care of the relation.
=> Relation based mapping error fix

src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts, src/app/home/b2b-flows/b2b-flows.component.ts
=> Defect DS-511 fixed

src/app/home/b2b-flows/b2b-flows.component.ts
=> Success msg to show name instead of id

src/app/home/api-keys/api-keys-manage/list-flow/list-flow.component.ts, src/app/home/api-keys/api-keys-manage/list-function/list-function.component.ts
=> Defect DS-518 fixed

src/app/home/b2b-flows-manage/b2b-flows-manage.component.ts, src/app/home/b2b-flows/b2b-flows.component.ts
=> Fixing the reopen issue
